### ISSUE TITLE
Cannot update the start date of the apprenticeship

### ISSUE THREAD

**Issue by mr-woodapple** [mr-woodapple/ASBNApp#56]
**Repro:**

- Load a .json file (new or existing) and go to the "Settings" page
- Try to change the "Apprenticeship start date..."

**Todo:**

- [ ] Make sure the bottom of the date picker is visible
- [ ] Add a "Save" button to the bottom of the picker 
- [ ] Make sure the date updates, if the user taps elsewhere on the page
